-- =============================================================================
-- V1__init.sql  (replace only the seed procedure section — full file follows)
-- Fix: split the two-row unit INSERT into two single-row INSERTs so that
-- RETURNING id INTO v_unit_101_id works correctly (scalar INTO requires exactly
-- one returned row; inserting both units in one statement caused
-- "query returned more than one row" → aborted transaction → registration fail).
-- =============================================================================

-- ─────────────────────────────────────────────────────────────────────────────
-- TENANTS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tenants (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    subdomain     VARCHAR(255) NOT NULL,
    status        VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    street_address VARCHAR(255),
    city           VARCHAR(100),
    state          VARCHAR(100),
    zip_code       VARCHAR(10),
    phone          VARCHAR(20),
    email          VARCHAR(255),
    account_owner  VARCHAR(255),
    account_url    VARCHAR(255),
    CONSTRAINT uq_tenants_subdomain UNIQUE (subdomain)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_tenants_name_lower ON tenants (LOWER(name));

INSERT INTO tenants (id, name, subdomain, status)
SELECT 0, 'Platform', 'platform', 'ACTIVE'
WHERE NOT EXISTS (SELECT 1 FROM tenants WHERE id = 0);

SELECT setval(
    pg_get_serial_sequence('tenants', 'id'),
    GREATEST((SELECT COALESCE(MAX(id), 0) FROM tenants), 1)
);


-- ─────────────────────────────────────────────────────────────────────────────
-- SUBSCRIPTIONS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS subscriptions (
    id                      BIGSERIAL PRIMARY KEY,
    tenant_id               BIGINT       NOT NULL,
    unit_limit              INT          NOT NULL DEFAULT 15,
    status                  VARCHAR(50),
    plan_name               VARCHAR(100),
    next_billing_date       DATE,
    plan                    VARCHAR(20)  NOT NULL DEFAULT 'FREE',
    plan_selected           BOOLEAN      NOT NULL DEFAULT FALSE,
    plan_selected_at        TIMESTAMP,
    stripe_customer_id      VARCHAR(100),
    stripe_subscription_id  VARCHAR(100),
    created_at              TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT subscriptions_status_check
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED'))
);


-- ─────────────────────────────────────────────────────────────────────────────
-- USERS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id             BIGINT       NOT NULL,
    email                 VARCHAR(255) NOT NULL,
    password              VARCHAR(255) NOT NULL,
    role                  VARCHAR(50)  NOT NULL,
    status                VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    name                  VARCHAR(255),
    first_name            VARCHAR(255) NOT NULL DEFAULT 'Unknown',
    last_name             VARCHAR(255) NOT NULL DEFAULT 'User',
    temporary_password    BOOLEAN      NOT NULL DEFAULT FALSE,
    temp_password_expiry  TIMESTAMP,
    created_at            TIMESTAMPTZ(6),
    CONSTRAINT users_role_check CHECK (
        role IN ('PLATFORM_ADMIN', 'TENANT_ADMIN', 'MANAGER', 'VIEWER')
    )
);

CREATE INDEX IF NOT EXISTS idx_users_tenant_id ON users(tenant_id);
CREATE INDEX IF NOT EXISTS idx_users_email     ON users(email);


-- ─────────────────────────────────────────────────────────────────────────────
-- PASSWORD RESET TOKENS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id         BIGSERIAL PRIMARY KEY,
    tenant_id  BIGINT       NOT NULL,
    user_id    BIGINT       NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    expires_at TIMESTAMPTZ  NOT NULL,
    used       BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_password_reset_token_hash ON password_reset_tokens(token_hash);
CREATE        INDEX IF NOT EXISTS idx_password_reset_user      ON password_reset_tokens(user_id);
CREATE        INDEX IF NOT EXISTS idx_password_reset_tenant    ON password_reset_tokens(tenant_id);


-- ─────────────────────────────────────────────────────────────────────────────
-- ASSOCIATIONS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS associations (
    id                BIGSERIAL PRIMARY KEY,
    tenant_id         BIGINT       NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    name              VARCHAR(150) NOT NULL,
    status            VARCHAR(20)  NOT NULL,
    street_address    VARCHAR(255),
    city              VARCHAR(100),
    state             VARCHAR(100),
    zip_code          VARCHAR(20),
    tax_identity_type VARCHAR(50),
    tax_payer_id      VARCHAR(50),
    tax_pending       BOOLEAN      NOT NULL DEFAULT FALSE,
    total_units       INT                   DEFAULT 0,
    created_at        TIMESTAMPTZ(6),
    updated_at        TIMESTAMPTZ(6)
);

CREATE INDEX IF NOT EXISTS idx_association_tenant_id ON associations(tenant_id);


-- ─────────────────────────────────────────────────────────────────────────────
-- UNITS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS units (
    id                BIGSERIAL PRIMARY KEY,
    tenant_id         BIGINT          NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    association_id    BIGINT          NOT NULL REFERENCES associations(id) ON DELETE CASCADE,
    unit_number       VARCHAR(100)    NOT NULL,
    street            VARCHAR(255),
    city              VARCHAR(255),
    state             VARCHAR(255),
    zip_code          VARCHAR(20),
    occupancy_status  VARCHAR(50)     NOT NULL,
    balance           NUMERIC(10,2)   NOT NULL DEFAULT 0,
    renter_first_name VARCHAR(100),
    renter_last_name  VARCHAR(100),
    renter_email      VARCHAR(255),
    renter_phone      VARCHAR(20),
    created_at        TIMESTAMPTZ(6)  NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ(6)
);

CREATE INDEX IF NOT EXISTS idx_units_tenant_id      ON units(tenant_id);
CREATE INDEX IF NOT EXISTS idx_units_association_id ON units(association_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_units_association_unit_number ON units(association_id, unit_number);
CREATE INDEX IF NOT EXISTS idx_units_renter_email   ON units(renter_email) WHERE renter_email IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_units_renter_phone   ON units(renter_phone) WHERE renter_phone IS NOT NULL;


-- ─────────────────────────────────────────────────────────────────────────────
-- OWNERS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS owners (
    id              BIGSERIAL PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL,
    association_id  BIGINT       REFERENCES associations(id),
    first_name      VARCHAR(100) NOT NULL,
    last_name       VARCHAR(100) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    alt_email       VARCHAR(255),
    phone           VARCHAR(50)  NOT NULL,
    alt_phone       VARCHAR(50),
    primary_street  VARCHAR(255) NOT NULL,
    primary_city    VARCHAR(100) NOT NULL,
    primary_state   VARCHAR(100) NOT NULL,
    primary_zip     VARCHAR(20)  NOT NULL,
    alt_street      VARCHAR(255),
    alt_city        VARCHAR(100),
    alt_state       VARCHAR(100),
    alt_zip         VARCHAR(20),
    created_at      TIMESTAMPTZ(6),
    updated_at      TIMESTAMPTZ(6),
    CONSTRAINT uq_owners_tenant_email UNIQUE (tenant_id, email)
);

CREATE INDEX IF NOT EXISTS idx_owners_tenant_id      ON owners(tenant_id);
CREATE INDEX IF NOT EXISTS idx_owners_email          ON owners(email);
CREATE INDEX IF NOT EXISTS idx_owners_association_id ON owners(association_id) WHERE association_id IS NOT NULL;


-- ─────────────────────────────────────────────────────────────────────────────
-- UNIT_OWNERS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS unit_owners (
    id              BIGSERIAL PRIMARY KEY,
    tenant_id       BIGINT  NOT NULL,
    unit_id         BIGINT  NOT NULL REFERENCES units(id)  ON DELETE CASCADE,
    owner_id        BIGINT  NOT NULL REFERENCES owners(id) ON DELETE CASCADE,
    is_board_member BOOLEAN NOT NULL DEFAULT FALSE,
    designation     VARCHAR(50),
    term_start_date DATE,
    term_end_date   DATE,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    is_primary      BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ(6),
    CONSTRAINT uq_unit_owners_unit_owner UNIQUE (unit_id, owner_id)
);

CREATE INDEX IF NOT EXISTS idx_unit_owners_unit_id   ON unit_owners(unit_id);
CREATE INDEX IF NOT EXISTS idx_unit_owners_owner_id  ON unit_owners(owner_id);
CREATE INDEX IF NOT EXISTS idx_unit_owners_tenant_id ON unit_owners(tenant_id);


-- ─────────────────────────────────────────────────────────────────────────────
-- UNIT INVOICES
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS unit_invoices (
    id              BIGSERIAL     NOT NULL,
    tenant_id       BIGINT        NOT NULL,
    unit_id         BIGINT        NOT NULL REFERENCES units(id) ON DELETE CASCADE,
    association_id  BIGINT        NOT NULL,
    invoice_date    DATE          NOT NULL,
    due_date        DATE          NOT NULL,
    total_amount    NUMERIC(10,2) NOT NULL,
    status          VARCHAR(20)   NOT NULL DEFAULT 'UNPAID',
    notes           TEXT,
    created_at      TIMESTAMP     NOT NULL DEFAULT NOW(),
    CONSTRAINT pk_unit_invoices PRIMARY KEY (id),
    CONSTRAINT chk_unit_invoices_status CHECK (status IN ('UNPAID', 'PAID', 'OVERDUE'))
);

CREATE TABLE IF NOT EXISTS unit_invoice_line_items (
    id                   BIGSERIAL     NOT NULL,
    invoice_id           BIGINT        NOT NULL REFERENCES unit_invoices(id) ON DELETE CASCADE,
    description          VARCHAR(255)  NOT NULL,
    income_account_id    BIGINT        NOT NULL,
    income_account_name  VARCHAR(255)  NOT NULL,
    amount               NUMERIC(10,2) NOT NULL,
    CONSTRAINT pk_unit_invoice_line_items PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_unit_invoices_tenant_id   ON unit_invoices(tenant_id);
CREATE INDEX IF NOT EXISTS idx_unit_invoices_unit_id     ON unit_invoices(unit_id);
CREATE INDEX IF NOT EXISTS idx_unit_invoices_association ON unit_invoices(association_id);
CREATE INDEX IF NOT EXISTS idx_unit_invoices_due_date    ON unit_invoices(due_date);
CREATE INDEX IF NOT EXISTS idx_unit_invoice_line_items_invoice_id ON unit_invoice_line_items(invoice_id);


-- ─────────────────────────────────────────────────────────────────────────────
-- VENDORS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS vendors (
    id                 BIGSERIAL    PRIMARY KEY,
    tenant_id          BIGINT       NOT NULL,
    first_name         VARCHAR(100) NOT NULL,
    last_name          VARCHAR(100) NOT NULL,
    company_name       VARCHAR(255) NOT NULL,
    service_category   VARCHAR(100) NOT NULL,
    email              VARCHAR(255) NOT NULL,
    alt_email          VARCHAR(255),
    mobile_phone       VARCHAR(50),
    work_phone         VARCHAR(50),
    home_phone         VARCHAR(50),
    website            VARCHAR(255),
    street             VARCHAR(255) NOT NULL,
    city               VARCHAR(100) NOT NULL,
    state              VARCHAR(100) NOT NULL,
    zip_code           VARCHAR(10)  NOT NULL,
    country            VARCHAR(100),
    tax_identity_type  VARCHAR(100),
    tax_payer_id       VARCHAR(100),
    insurance_provider VARCHAR(255),
    policy_number      VARCHAR(100),
    insurance_expiry   DATE,
    notes              TEXT,
    status             VARCHAR(20)  NOT NULL,
    created_at         TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMP,
    CONSTRAINT uq_vendors_tenant_email UNIQUE (tenant_id, email),
    CONSTRAINT chk_vendors_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX IF NOT EXISTS idx_vendors_tenant_id       ON vendors(tenant_id);
CREATE INDEX IF NOT EXISTS idx_vendors_tenant_status   ON vendors(tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_vendors_tenant_category ON vendors(tenant_id, service_category);
CREATE INDEX IF NOT EXISTS idx_vendors_email           ON vendors(email);


-- ─────────────────────────────────────────────────────────────────────────────
-- COMMUNICATION MESSAGES & DELIVERIES
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS communication_messages (
    id              BIGSERIAL PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL,
    association_id  BIGINT,
    type            VARCHAR(20),
    subject         VARCHAR(255),
    title           VARCHAR(255),
    body            TEXT,
    status          VARCHAR(20),
    scheduled_at    TIMESTAMPTZ(6),
    sent_at         TIMESTAMPTZ(6),
    template_id     BIGINT,
    recipient_label VARCHAR(120),
    created_at      TIMESTAMPTZ(6)
);

CREATE INDEX IF NOT EXISTS idx_msg_tenant_id        ON communication_messages(tenant_id);
CREATE INDEX IF NOT EXISTS idx_msg_association_id   ON communication_messages(association_id);
CREATE INDEX IF NOT EXISTS idx_msg_tenant_type      ON communication_messages(tenant_id, type);
CREATE INDEX IF NOT EXISTS idx_msg_status_scheduled ON communication_messages(status, scheduled_at)
    WHERE status = 'SCHEDULED';

CREATE TABLE IF NOT EXISTS communication_deliveries (
    id            BIGSERIAL PRIMARY KEY,
    tenant_id     BIGINT NOT NULL,
    message_id    BIGINT REFERENCES communication_messages(id) ON DELETE CASCADE,
    owner_id      BIGINT,
    vendor_id     BIGINT,
    email         VARCHAR(255),
    phone         VARCHAR(50),
    channel       VARCHAR(20),
    status        VARCHAR(20),
    retry_count   INT         DEFAULT 0,
    error_message TEXT,
    delivered_at  TIMESTAMP,
    created_at    TIMESTAMPTZ(6)
);

CREATE INDEX IF NOT EXISTS idx_delivery_tenant_id  ON communication_deliveries(tenant_id);
CREATE INDEX IF NOT EXISTS idx_delivery_message_id ON communication_deliveries(message_id);


-- ─────────────────────────────────────────────────────────────────────────────
-- COMMUNICATION TEMPLATES
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS communication_templates (
    id             BIGSERIAL PRIMARY KEY,
    tenant_id      BIGINT       NOT NULL,
    name           VARCHAR(255),
    level          VARCHAR(20),
    category       VARCHAR(100),
    description    VARCHAR(255),
    recipient_type VARCHAR(100),
    subject        VARCHAR(255),
    content        TEXT,
    created_at     TIMESTAMPTZ(6)
);

CREATE INDEX IF NOT EXISTS idx_comm_templates_tenant_id ON communication_templates(tenant_id);


-- ─────────────────────────────────────────────────────────────────────────────
-- CHART OF ACCOUNTS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS chart_of_accounts (
    id           BIGSERIAL    PRIMARY KEY,
    tenant_id    BIGINT       NOT NULL,
    account_code VARCHAR(20)  NOT NULL,
    account_name VARCHAR(100) NOT NULL,
    account_type VARCHAR(20)  NOT NULL
        CONSTRAINT chk_coa_account_type
        CHECK (account_type IN ('ASSETS','LIABILITIES','EQUITY','INCOME','EXPENSES')),
    notes        TEXT,
    is_deleted   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMP    NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_coa_tenant_code UNIQUE (tenant_id, account_code)
);

CREATE INDEX IF NOT EXISTS idx_coa_tenant_id   ON chart_of_accounts(tenant_id)              WHERE is_deleted = FALSE;
CREATE INDEX IF NOT EXISTS idx_coa_tenant_type ON chart_of_accounts(tenant_id, account_type) WHERE is_deleted = FALSE;
CREATE INDEX IF NOT EXISTS idx_coa_tenant_name ON chart_of_accounts(tenant_id, account_name) WHERE is_deleted = FALSE;


-- ─────────────────────────────────────────────────────────────────────────────
-- JOURNAL ENTRIES & LINES
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS journal_entries (
    id              BIGSERIAL   PRIMARY KEY,
    tenant_id       BIGINT      NOT NULL,
    association_id  BIGINT      NOT NULL,
    date            DATE        NOT NULL,
    memo            TEXT,
    attachment_path VARCHAR(255),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS journal_lines (
    id          BIGSERIAL     PRIMARY KEY,
    journal_id  BIGINT        NOT NULL REFERENCES journal_entries(id) ON DELETE CASCADE,
    account_id  BIGINT        NOT NULL,
    description VARCHAR(255),
    debit       NUMERIC(15,2) NOT NULL DEFAULT 0,
    credit      NUMERIC(15,2) NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_journal_tenant     ON journal_entries(tenant_id);
CREATE INDEX IF NOT EXISTS idx_journal_assoc_date ON journal_entries(tenant_id, association_id, date);


-- ─────────────────────────────────────────────────────────────────────────────
-- LEDGER ENTRIES
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ledger_entries (
    id               BIGSERIAL      PRIMARY KEY,
    tenant_id        BIGINT         NOT NULL,
    journal_id       BIGINT,
    account_id       BIGINT         NOT NULL,
    association_id   BIGINT         NOT NULL,
    date             DATE           NOT NULL,
    description      TEXT,
    debit            NUMERIC(19,4)  NOT NULL DEFAULT 0,
    credit           NUMERIC(19,4)  NOT NULL DEFAULT 0,
    accounting_basis VARCHAR(10)    NOT NULL
        CONSTRAINT chk_ledger_basis CHECK (accounting_basis IN ('CASH','ACCRUAL')),
    created_at       TIMESTAMP      NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ledger_tenant_association ON ledger_entries(tenant_id, association_id);
CREATE INDEX IF NOT EXISTS idx_ledger_tenant_account     ON ledger_entries(tenant_id, account_id);
CREATE INDEX IF NOT EXISTS idx_ledger_tenant_date        ON ledger_entries(tenant_id, date DESC);


-- ─────────────────────────────────────────────────────────────────────────────
-- BANK ACCOUNTS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS bank_accounts (
    id                    BIGSERIAL     PRIMARY KEY,
    tenant_id             BIGINT        NOT NULL,
    association_id        BIGINT        NOT NULL,
    bank_account_name     VARCHAR(255)  NOT NULL,
    account_type          VARCHAR(20)   NOT NULL
        CHECK (account_type IN ('CHECKING','SAVINGS','MONEY_MARKET')),
    country               VARCHAR(100)  NOT NULL DEFAULT 'United States',
    routing_number        VARCHAR(9)    NOT NULL,
    account_number_masked VARCHAR(10)   NOT NULL,
    account_notes         TEXT,
    check_printing_enabled BOOLEAN      NOT NULL DEFAULT FALSE,
    balance               NUMERIC(15,2) NOT NULL DEFAULT 0,
    created_at            TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bank_accounts_tenant ON bank_accounts(tenant_id);
CREATE INDEX IF NOT EXISTS idx_bank_accounts_assoc  ON bank_accounts(tenant_id, association_id);


-- ─────────────────────────────────────────────────────────────────────────────
-- BILLS, BILL LINE ITEMS, BILL ATTACHMENTS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS bills (
    id                        BIGSERIAL     PRIMARY KEY,
    tenant_id                 BIGINT        NOT NULL,
    bill_number               VARCHAR(20)   NOT NULL,
    vendor_id                 BIGINT        NOT NULL,
    association_id            BIGINT        NOT NULL,
    issue_date                DATE          NOT NULL,
    due_date                  DATE          NOT NULL,
    status                    VARCHAR(10)   NOT NULL DEFAULT 'UNPAID'
        CHECK (status IN ('UNPAID','PAID','OVERDUE')),
    total_amount              NUMERIC(15,2) NOT NULL DEFAULT 0,
    memo                      TEXT,
    paid_at                   TIMESTAMPTZ,
    paid_from_bank_account_id BIGINT,
    created_at                TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS bill_line_items (
    id                 BIGSERIAL     PRIMARY KEY,
    bill_id            BIGINT        NOT NULL REFERENCES bills(id) ON DELETE CASCADE,
    description        VARCHAR(255),
    expense_account_id BIGINT        NOT NULL,
    amount             NUMERIC(15,2) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS bill_attachments (
    id                BIGSERIAL    PRIMARY KEY,
    tenant_id         BIGINT       NOT NULL,
    bill_id           BIGINT       NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    stored_path       VARCHAR(500) NOT NULL,
    content_type      VARCHAR(50)  NOT NULL,
    file_size         BIGINT       NOT NULL,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE        INDEX IF NOT EXISTS idx_bills_tenant         ON bills(tenant_id);
CREATE        INDEX IF NOT EXISTS idx_bills_tenant_status  ON bills(tenant_id, status);
CREATE        INDEX IF NOT EXISTS idx_bills_tenant_assoc   ON bills(tenant_id, association_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_bills_number          ON bills(tenant_id, bill_number);
CREATE        INDEX IF NOT EXISTS idx_bill_line_items_bill ON bill_line_items(bill_id);
CREATE        INDEX IF NOT EXISTS idx_bill_attachments_bill   ON bill_attachments(bill_id);
CREATE        INDEX IF NOT EXISTS idx_bill_attachments_tenant ON bill_attachments(tenant_id, bill_id);


-- ─────────────────────────────────────────────────────────────────────────────
-- HELP TABLES
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS support_tickets (
    id          BIGSERIAL  PRIMARY KEY,
    tenant_id   BIGINT     NOT NULL,
    user_id     BIGINT     NOT NULL,
    subject     VARCHAR(255) NOT NULL,
    description TEXT         NOT NULL,
    status      VARCHAR(20)  NOT NULL DEFAULT 'OPEN'
        CONSTRAINT chk_support_tickets_status
        CHECK (status IN ('OPEN','IN_PROGRESS','RESOLVED','CLOSED')),
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS feature_suggestions (
    id          BIGSERIAL  PRIMARY KEY,
    tenant_id   BIGINT     NOT NULL,
    user_id     BIGINT     NOT NULL,
    title       VARCHAR(255) NOT NULL,
    description TEXT         NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_support_tickets_tenant_id   ON support_tickets(tenant_id);
CREATE INDEX IF NOT EXISTS idx_support_tickets_tenant_user ON support_tickets(tenant_id, user_id);
CREATE INDEX IF NOT EXISTS idx_feature_suggestions_tenant_id   ON feature_suggestions(tenant_id);
CREATE INDEX IF NOT EXISTS idx_feature_suggestions_tenant_user ON feature_suggestions(tenant_id, user_id);


-- ─────────────────────────────────────────────────────────────────────────────
-- BUDGETS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS budgets (
    id             BIGSERIAL    PRIMARY KEY,
    tenant_id      BIGINT       NOT NULL,
    association_id BIGINT,
    name           VARCHAR(255) NOT NULL,
    fiscal_year    INT          NOT NULL,
    start_date     DATE         NOT NULL,
    end_date       DATE         NOT NULL,
    status         VARCHAR(20)  NOT NULL DEFAULT 'DRAFT'
        CONSTRAINT chk_budgets_status
        CHECK (status IN ('DRAFT','ACTIVE','CLOSED')),
    notes          TEXT,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS budget_line_items (
    id              BIGSERIAL      PRIMARY KEY,
    budget_id       BIGINT         NOT NULL REFERENCES budgets(id) ON DELETE CASCADE,
    account_id      BIGINT         NOT NULL,
    budgeted_amount NUMERIC(15,2)  NOT NULL DEFAULT 0,
    notes           TEXT,
    CONSTRAINT uq_budget_line_account UNIQUE (budget_id, account_id)
);

CREATE INDEX IF NOT EXISTS idx_budgets_tenant_id      ON budgets(tenant_id);
CREATE INDEX IF NOT EXISTS idx_budgets_association_id ON budgets(association_id);
CREATE INDEX IF NOT EXISTS idx_budgets_fiscal_year    ON budgets(tenant_id, fiscal_year);
CREATE INDEX IF NOT EXISTS idx_budget_items_budget    ON budget_line_items(budget_id);
CREATE INDEX IF NOT EXISTS idx_budget_items_account   ON budget_line_items(account_id);


-- ─────────────────────────────────────────────────────────────────────────────
-- SEED PROCEDURE  (fixed: split unit INSERT into two separate single-row INSERTs)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE PROCEDURE seed_tenant_data(p_tenant_id BIGINT)
LANGUAGE plpgsql
AS $$
DECLARE
    v_association_id BIGINT;
    v_unit_101_id    BIGINT;
    v_owner_id       BIGINT;
BEGIN

    -- 1. Chart of Accounts
    INSERT INTO chart_of_accounts
        (tenant_id, account_code, account_name, account_type, notes, is_deleted, created_at)
    VALUES
        (p_tenant_id, '1000', 'Cash - Operating Account',  'ASSETS',      'Primary bank account',             false, NOW()),
        (p_tenant_id, '1010', 'Cash - Reserve Account',    'ASSETS',      'Reserve fund bank account',        false, NOW()),
        (p_tenant_id, '1020', 'Cash - Main Checking',      'ASSETS',      'Main checking account',            false, NOW()),
        (p_tenant_id, '1030', 'Cash - Savings Account',    'ASSETS',      'Savings account',                  false, NOW()),
        (p_tenant_id, '1100', 'Accounts Receivable',       'ASSETS',      'Owner dues and fees owed to HOA',  false, NOW()),
        (p_tenant_id, '1200', 'Prepaid Insurance',         'ASSETS',      'Prepaid insurance expenses',       false, NOW()),
        (p_tenant_id, '1500', 'Property & Equipment',      'ASSETS',      'Fixed assets',                     false, NOW()),
        (p_tenant_id, '2000', 'Accounts Payable',          'LIABILITIES', 'Amounts owed to vendors',          false, NOW()),
        (p_tenant_id, '2100', 'Accrued Expenses',          'LIABILITIES', 'Accrued but unpaid expenses',      false, NOW()),
        (p_tenant_id, '2200', 'Deferred Revenue',          'LIABILITIES', 'Prepaid dues not yet earned',      false, NOW()),
        (p_tenant_id, '2500', 'Long-term Debt',            'LIABILITIES', 'Long-term loans and debt',         false, NOW()),
        (p_tenant_id, '3000', 'Retained Earnings',         'EQUITY',      'Accumulated surplus / deficit',    false, NOW()),
        (p_tenant_id, '3100', 'Current Year Earnings',     'EQUITY',      'Current year net income',          false, NOW()),
        (p_tenant_id, '4000', 'HOA Fees',                  'INCOME',      'Monthly assessment income',        false, NOW()),
        (p_tenant_id, '4100', 'Late Fees',                 'INCOME',      'Late fee income',                  false, NOW()),
        (p_tenant_id, '4200', 'Violation Fines',           'INCOME',      'Fines for rule violations',        false, NOW()),
        (p_tenant_id, '4300', 'Interest Income',           'INCOME',      'Interest earned on accounts',      false, NOW()),
        (p_tenant_id, '5000', 'Landscaping',               'EXPENSES',    'Landscaping vendor costs',         false, NOW()),
        (p_tenant_id, '5100', 'Maintenance & Repairs',     'EXPENSES',    'General maintenance costs',        false, NOW()),
        (p_tenant_id, '5200', 'Utilities',                 'EXPENSES',    'Water, electricity, gas',          false, NOW()),
        (p_tenant_id, '5300', 'Insurance',                 'EXPENSES',    'Property and liability insurance', false, NOW()),
        (p_tenant_id, '5400', 'Administrative Expenses',   'EXPENSES',    'Office, printing, postage',        false, NOW())
    ON CONFLICT (tenant_id, account_code) DO NOTHING;

    -- 2. Sample Association
    INSERT INTO associations
        (tenant_id, name, street_address, city, state, zip_code, status, created_at)
    VALUES
        (p_tenant_id, 'Sample HOA Community', '100 Community Drive',
         'Los Angeles', 'CA', '90001', 'ACTIVE', NOW())
    ON CONFLICT DO NOTHING
    RETURNING id INTO v_association_id;

    IF v_association_id IS NULL THEN
        SELECT id INTO v_association_id FROM associations
        WHERE tenant_id = p_tenant_id AND name = 'Sample HOA Community'
        LIMIT 1;
    END IF;

    IF v_association_id IS NOT NULL THEN

        -- 3. Sample Units  ← FIX: each INSERT is a single row so RETURNING INTO scalar works
        INSERT INTO units
            (tenant_id, association_id, unit_number, street, city, state,
             zip_code, occupancy_status, balance, created_at)
        VALUES
            (p_tenant_id, v_association_id, '101',
             '100 Community Drive Unit 101', 'Los Angeles', 'CA', '90001',
             'OWNER_OCCUPIED', 0, NOW())
        ON CONFLICT DO NOTHING
        RETURNING id INTO v_unit_101_id;

        IF v_unit_101_id IS NULL THEN
            SELECT id INTO v_unit_101_id FROM units
            WHERE tenant_id = p_tenant_id
              AND association_id = v_association_id
              AND unit_number = '101'
            LIMIT 1;
        END IF;

        -- Insert unit 102 separately (no need to capture its id)
        INSERT INTO units
            (tenant_id, association_id, unit_number, street, city, state,
             zip_code, occupancy_status, balance, created_at)
        VALUES
            (p_tenant_id, v_association_id, '102',
             '100 Community Drive Unit 102', 'Los Angeles', 'CA', '90001',
             'VACANT', 0, NOW())
        ON CONFLICT DO NOTHING;

        -- 4. Sample Owner linked to Unit 101 via unit_owners
        IF v_unit_101_id IS NOT NULL THEN
            INSERT INTO owners
                (tenant_id, association_id, first_name, last_name, email, phone,
                 primary_street, primary_city, primary_state, primary_zip, created_at)
            VALUES
                (p_tenant_id, v_association_id,
                 'Sample', 'Owner', 'sample.owner@example.com', '(555) 000-0000',
                 '100 Community Drive Unit 101', 'Los Angeles', 'CA', '90001', NOW())
            ON CONFLICT (tenant_id, email) DO NOTHING
            RETURNING id INTO v_owner_id;

            IF v_owner_id IS NULL THEN
                SELECT id INTO v_owner_id FROM owners
                WHERE tenant_id = p_tenant_id
                  AND email = 'sample.owner@example.com'
                LIMIT 1;
            END IF;

            IF v_owner_id IS NOT NULL THEN
                INSERT INTO unit_owners
                    (tenant_id, unit_id, owner_id, is_board_member,
                     is_active, is_primary, created_at)
                VALUES
                    (p_tenant_id, v_unit_101_id, v_owner_id,
                     false, true, true, NOW())
                ON CONFLICT (unit_id, owner_id) DO NOTHING;
            END IF;
        END IF;

        -- 5. Sample Bank Account
        INSERT INTO bank_accounts
            (tenant_id, association_id, bank_account_name, account_type,
             country, routing_number, account_number_masked,
             account_notes, check_printing_enabled, balance, created_at)
        VALUES
            (p_tenant_id, v_association_id,
             'Operating Account', 'CHECKING', 'United States',
             '000000000', '****0000',
             'Default operating account — update routing and account numbers before use',
             false, 0.00, NOW())
        ON CONFLICT DO NOTHING;

    END IF;

    -- 6. Communication Templates
    INSERT INTO communication_templates
        (tenant_id, name, level, category, description, subject, content, created_at)
    VALUES
    (
        p_tenant_id,
        'Monthly HOA Fee Reminder', 'ASSOCIATION', 'BILLING',
        'Send to all owners to remind them of monthly dues',
        'HOA Fee Due — {{associationName}}',
        E'Dear {{ownerName}},\n\nThis is a friendly reminder that your monthly HOA assessment is due.\n\nAssociation: {{associationName}}\nUnit: {{unitNumber}}\n\nPlease make your payment by the due date to avoid late fees.\n\nThank you,\n{{associationName}} Management Team',
        NOW()
    ),
    (
        p_tenant_id,
        'Welcome New Owner', 'INDIVIDUAL', 'WELCOME',
        'Send to newly added owners',
        'Welcome to {{associationName}}, {{ownerName}}!',
        E'Dear {{ownerName}},\n\nWelcome to {{associationName}}! We are pleased to have you as a member of our community.\n\nYour unit number is {{unitNumber}}. If you have any questions, please do not hesitate to contact the management team.\n\nWarm regards,\n{{associationName}} Management',
        NOW()
    ),
    (
        p_tenant_id,
        'Board Meeting Notice', 'ASSOCIATION', 'ANNOUNCEMENT',
        'Notify all owners of upcoming board meetings',
        'Board Meeting Notice — {{associationName}}',
        E'Dear {{ownerName}},\n\nYou are cordially invited to attend the upcoming Board Meeting for {{associationName}}.\n\nDate: {{date}}\n\nAll residents are welcome to attend. Agenda items will be distributed prior to the meeting.\n\nBest regards,\nThe Board of Directors',
        NOW()
    )
    ON CONFLICT DO NOTHING;

    RAISE NOTICE 'Seed data created for tenant %', p_tenant_id;
END;
$$;